<?php
return [
    // Home Page
    'Home' => 'Home',
    'number_of_Experience' => '10 +',
    'Years' => 'Years',
    'Of Experience' => 'Of Experience',
    'About Our Company' => 'About Our Company',
    'About_Title' => 'Awesome services from industrial company',

    'About_Desc' => 'When I founded ASAD 10 years ago, I was driven by my ambition to develop an insightful success story through contributing to the construction development on the land of Kuwait by providing high-level services in accordance to quality, security and safety standards.',

    'Point1' => 'Through our willpower and adherence to our values, we have successfully expanded our services to satisfy the demands of the construction market in both public and private sectors to exceed our clients\' expectations.',

    'Point2' => 'This is the story of ASAD, but it is only the beginning. We are ideally situated to engage new prospects in the upcoming years, encouraged by the unmatched aspiration and determination towards distinction in everything we do. As we write the next chapter of ASAD, we look forward to sharing our success with you',

    'Point3' => 'Our commitments extends beyond the boundaries of commercial and contractual interests to achieve a sustainable value through our accountable leadership and innovative practices that aim to create an imprint as a national company which shoulders its social responsibilities towards society and environment in which it operates.',

    'Loyal_Customer' => 'Eng. Wael Soliman',
    'Customer_Posation' => 'FOUNDER & CEO',
    'More_About_Us' => 'More About Us',
    'work_process_title' => 'We strive to be a step ahead',
    'work_process_desc' => 'The four steps working process to get amazing works',
    'Project_Research' => 'Project Research',
    'Project_Research_desc' => 'One of the key components of best logistics solutions industy',
    'Development' => 'Development',
    'Development_desc' => 'One of the key components of best logistics solutions industy',
    'Team_Works' => 'Team Works',
    'Team_Works_desc' => 'One of the key components of best logistics solutions industy',
    'Quality_Finished' => 'Quality Finished',
    'Quality_Finished_desc' => 'One of the key components of best logistics solutions industy',
    'Watch_Our_Video' => 'Watch Our Video',
    'Watch_Our_Video_Desc' => 'We help our clients realize their business ideas and achieve great results',
    'Great_Company_Backup' => 'Great Company Backup',
    'We_Are_Professional_Factory_Experts' => 'We Are Professional Factory Experts',
    'Great_Company_Backup_desc' => 'Factory companies are an important part of the global economy, as they produce the goods that are used by people around the world. However the impact of factory companies on the environment.',
    'Innovative Solution' => 'Innovative Solution',
    'Innovative_Solution_Desc' => 'Class ad porta tempus per him accumsan posuer felis sollicitudin primis malesuada',
    'Experienced Team' => 'Experienced Team',
    'Experienced_Team_Desc' => 'Class ad porta tempus per him accumsan posuer felis sollicitudin primis malesuada',

    // About Page
    'About Us' => 'About Us',
    'More About Us' => 'More About Us',
    'Our mission is save people from pollution' => 'Our mission is save people from pollution',
    'Consequat risus cum congue facilisis in egestas etiam senectus...' => 'Consequat risus cum congue facilisis in egestas etiam senectus...',
    '25+' => '25+',
    'Experience' => 'Experience',
    'Eamlessly conceptualize go forward total linkage' => 'Eamlessly conceptualize go forward total linkage',
    'Whiteboard multifuional applications rather than' => 'Whiteboard multifuional applications rather than',
    'Applications rather than lived reliable functionale' => 'Applications rather than lived reliable functionale',
    'Leverage other quality ideas synestic outsourcing' => 'Leverage other quality ideas synestic outsourcing',
    '7.2M+ User' => '7.2M+ User',
    'Book Your Service' => 'Book Your Service',
    'Wonderful visionary dream we see for our client’s' => 'Wonderful visionary dream we see for our client’s',
    'Nec platea est metus imperdiet litora natoque eros posuere ac venenatis...' => 'Nec platea est metus imperdiet litora natoque eros posuere ac venenatis...',
    'Global Country' => 'Global Country',
    'Company Growth' => 'Company Growth',
    'Satisfied Customers' => 'Satisfied Customers',
    'Customer Rating' => 'Customer Rating',
    'Looking for qualified professionals to do renovations to your existing home in Los Angeles?' => 'Looking for qualified professionals to do renovations to your existing home in Los Angeles?',
    'View Our Services' => 'View Our Services',
    'Watch Our Story' => 'Watch Our Story',
    'Get In Touch' => 'Get In Touch',
    'Needs Help? Let’s Get in Touch' => 'Needs Help? Let’s Get in Touch',
    'Send Message' => 'Send Message',
    'Service Station' => 'Service Station',
    '258D Mark Avenue Berlin.' => '258D Mark Avenue Berlin.',
    'Make A Quote' => 'Make A Quote',
    'Call Us 24/7' => 'Call Us 24/7',
    'Contact Us' => 'Contact Us',
];
