<?php
return [
    // Home Page
    'Home' => 'Home',
    '25' => '25',
    'Years' => 'Years',
    'Of Experience' => 'Of Experience',
    'About Our Company' => 'About Our Company',
    'About_Title' => 'Awesome services from industrial company',
    'About_Desc' => 'A factory is a business that produces goods or products. These goods can range from consumer products such as clothing and electronics to industrial products such as machinery and equipment. Factories are typically large buildings or complexes that are equipped. Factory companies employ a large number of people, from factory workers and supervisors to managers and executives.',
    'Point1' => '5 Year Warranty on Workmanship',
    'Point2' => 'Every Project is Run by a Team of Experts',
    'Point3' => 'We Save You Time, Money, and Space',
    'Loyal_Customer' => '15k Loyal Customer',
    'More_About_Us' => 'More About Us',
    'work_process_title' => 'We strive to be a step ahead',
    'work_process_desc' => 'The four steps working process to get amazing works',
    'Project_Research' => 'Project Research',
    'Project_Research_desc' => 'One of the key components of best logistics solutions industy',
    'Development' => 'Development',
    'Development_desc' => 'One of the key components of best logistics solutions industy',
    'Team_Works' => 'Team Works',
    'Team_Works_desc' => 'One of the key components of best logistics solutions industy',
    'Quality_Finished' => 'Quality Finished',
    'Quality_Finished_desc' => 'One of the key components of best logistics solutions industy',
    'Watch_Our_Video' => 'Watch Our Video',
    'Watch_Our_Video_Desc' => 'We help our clients realize their business ideas and achieve great results',
    'Great_Company_Backup' => 'Great Company Backup',
    'We_Are_Professional_Factory_Experts' => 'We Are Professional Factory Experts',
    'Great_Company_Backup_desc' => 'Factory companies are an important part of the global economy, as they produce the goods that are used by people around the world. However the impact of factory companies on the environment.',
    'Innovative Solution' => 'Innovative Solution',
    'Innovative_Solution_Desc' => 'Class ad porta tempus per him accumsan posuer felis sollicitudin primis malesuada',
    'Experienced Team' => 'Experienced Team',
    'Experienced_Team_Desc' => 'Class ad porta tempus per him accumsan posuer felis sollicitudin primis malesuada',

];
